version: '3'

services:
  db:
    image: mysql:5.7.38
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - apps_network

networks:
  apps_network:
    external: true